feeds:
  - name: small-package
    repo: https://github.com/kenzok8/small-package.git
    packages:
      - luci-app-adguardhome
      - adguardhome
      - luci-app-openclash
      # - luci-app-openlist2
      # - openlist2
